### PR TITLE
[BUGFIX] Fix issue with interactive guideline

### LINKED ISSUE #20: Interactive guideline only works in primary chart
Interactive guideline now only works in primary chart of LWFPS

### PR DESCRIPTION
**Pull request by jeznag**
Fixes #20

### CODE REVIEW

**Comment by jufemaiz** [comment]
screenshot 2018-06-04 08 36 54

screenshot 2018-06-04 08 37 45

Extends beyond the graph canvases and into the zoom selector.

File: src/models/lineWithFocusPlusSecondaryChart.js [hunk 1]
```diff
@@ -452,7 +452,7 @@ nv.models.lineWithFocusPlusSecondaryChart = function() {
           .height(heightForInteractiveLayer)
```
Comment (jufemaiz) [inline src/models/lineWithFocusPlusSecondaryChart.js]: Above this ^^^:

```javascript
        var heightForInteractiveLayer = availableHeightPrimary;
        if (seriesSecondary.length) {
          heightForInteractiveLayer =
            secondaryChartHeight +
            legend.height() +
            availableHeightPrimary +
            marginSecondary.bottom +
            margin.top;
        }
```

The block sizes were incorrect.

The height for interactive layer's height is what the height of the overlay line. This is, in order, the sum of:

- Height of the Secondary Chart: `secondaryChartHeight`
- Bottom margin of the Secondary Chart: `marginSecondary.bottom`
- Height of the (Primary) Legend: `legend.height()`
- Top margin of the Primary Chart: `margin.top`
- Height of the Primary Chart: `availableHeightPrimary (proxy for primaryChartHeight)`
